### ISSUE TITLE
[QUESTION] How to use resource pack's specific textures ?

### ISSUE THREAD

**Issue by G1ll0u** [fonnymunkey/RLFoliage#5]
Hello guys,

I have my modpack with specific resourcepacks that I merge to make it look as I want.

I'm searching how to change falling_leaf textures.
My resourcepack provides textures under :

\assets\betterfoliage\textures\blocks\
AND
\assets\bettergrassandleaves\textures\blocks\

In these two last folders are located files named "falling_leaves_spruce"

Are these files normally changing falling leaf textures ?

Current texture :
![2024-07-19_21 32 07](https://github.com/user-attachments/assets/384b538a-28c7-4a87-b7c3-377ecd8b2db2)

Desired texture :
![falling_leaf_spruce_0](https://github.com/user-attachments/assets/4d323088-a700-4711-b2f4-fce73e1d88fb)

It takes a lot of time to reload Minecraft resôurce pack with Optifine... it takes approx. 3min everytime...

Is there documentation about how this mod uses textures provided by resource pack ?
Or will you be able to help me ?

Thanks in advance and have a lovely day.

PS: I use conquest_ resourcepack mixed with JSTR_modded.

**Comment by yesBad** [comment]
?

**Comment by G1ll0u** [comment]
sorry I'm editing it dont worry

**Comment by fonnymunkey** [comment]
Falling leaf textures are located in https://github.com/fonnymunkey/RLFoliage/tree/kotlin-1.12/src/main/resources/assets/betterfoliage/textures/blocks and will use the same path and naming for overriding with a resourcepack/resourceloader.

Falling leaf textures by default are 8x8 pixels and grayscale, as the coloring is dynamically rendered over the texture to allow for things such as seasonal/biome colors.

Your texture does work when placed in that path and named "falling_leaf_spruce_0.png", however it is very hard to see as it is a 32x32 sheet of multiple leaves instead of a single larger leaf.

If you want to override the default falling leaf textures with those textures, split that texture sheet into multiple 8x8 textures and name them "falling_leaf_spruce_0.png" "falling_leaf_spruce_1.png" "falling_leaf_spruce_x.png" etc. and place them in "betterfoliage/textures/blocks/"

As an aside, if you are going to be repeatedly reloading textures for testing resourcepacks, you should disable Conquest when you are testing, as it is a massive resourcepack that will contribute heavily to those load times.

**Comment by G1ll0u** [comment]
I found a workaround but I didn't know that the problem only affects falling_leaf_spruce_x. I'm able to replace other textures (like falling_leaf_default_x)

To make your mod use my custom falling leaves textures, I deleted spruce_leaves.json from `/conquest/assets/minecraft/models/block`
It altered rendering of spruce leaves making them look less good :

Normally :
![image](https://github.com/user-attachments/assets/bb20bf33-ad10-41dd-82d4-505ca0b25d9c)

Altered :
![image](https://github.com/user-attachments/assets/c3f64194-1c4a-4a22-a30f-4d1c8512058a)

but now your mod is using my custom textures located at `"\conquest\assets\betterfoliage\textures\blocks"` and it is what I wanted! But...

Here's the incrimined file :
[spruce_leaves.json file](https://github.com/user-attachments/files/17216276/spruce_leaves.json)
Formatted pastebin if you lazy :
[https://pastebin.com/FDFNwyeU](https://pastebin.com/FDFNwyeU)

I carefully read this file and it doesn't mention anything about falling leaves textures
I tried a lot of things editing this json but only removing it makes spruce falling leaves work

I think your mod probably has a problem when resource packs use json models for leaves.

I tested it in a minimal config :
<details><summary>system details</summary>
-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 11 (amd64) version 10.0
	Java Version: 21.0.4, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1448646912 bytes (1381 MB) / 4714397696 bytes (4496 MB) up to 12826181632 bytes (12232 MB)
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms4096m -Xmx12228m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.42 Cleanroom 0.2.3-alpha+build.5.run.696 Optifine OptiFine_1.12.2_HD_U_G6_pre1 13 mods loaded, 12 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                  | Version                   | Source                                              | Signature                                |
	|:------ |:------------------- |:------------------------- |:--------------------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft           | 1.12.2                    | minecraft.jar                                       | None                                     |
	| LCHIJA | mcp                 | 9.42                      | minecraft.jar                                       | None                                     |
	| LCHIJA | configanytime       | 3.0                       | cleanroom-0.2.3-alpha+build.5.run.696-universal.jar | None                                     |
	| LCHIJA | cleanroom           | 0.2.3-alpha               | cleanroom-0.2.3-alpha+build.5.run.696-universal.jar | None                                     |
	| LCHIJA | FML                 | 8.0.99.99                 | cleanroom-0.2.3-alpha+build.5.run.696-universal.jar | None                                     |
	| LCHIJA | forge               | 14.23.5.2860              | cleanroom-0.2.3-alpha+build.5.run.696-universal.jar | None                                     |
	| LCHIJA | mixinbooter         | 10.0                      | cleanroom-0.2.3-alpha+build.5.run.696-universal.jar | None                                     |
	| LCHIJA | fugue               | 1.12.2-0.16.3             | +Fugue-1.12.2-0.16.3.jar                            | None                                     |
	| LCHIJA | forgelin_continuous | 2.0.20.0                  | Forgelin-Continuous-2.0.20.0.jar                    | None                                     |
	| LCHIJA | forgelin            | 1.8.4                     | Forgelin-Continuous-2.0.20.0.jar                    | None                                     |
	| LCHIJA | betterfoliage       | 2.4.2                     | RLFoliage-MC1.12-2.4.2.jar                          | None                                     |
	| LCHIJA | tellme              | 0.7.0-dev.20200919.184303 | tellme-1.12.2-0.7.0-dev.20200919.184303.jar         | 2b03e1423915a189b8094816baa18f239d576dff |
	| UD     | scalar              | 2.11.1                    | minecraft.jar                                       | None                                     |

	Loaded coremods (and transformers): 
Fugue (+Fugue-1.12.2-0.16.3.jar)
  
BetterFoliageLoader (RLFoliage-MC1.12-2.4.2.jar)
  mods.betterfoliage.loader.BetterFoliageTransformer
Forgelin-Continuous (Forgelin-Continuous-2.0.20.0.jar)
  
ScalarLoadingPlugin (scalar-1.12.2-2.11.1.jar)
  
MixinBooter (cleanroom-0.2.3-alpha+build.5.run.696-universal.jar)
  
	GL info: No OpenGL context found in the current thread
	Launched Version: 1.12.2
	LWJGL: 3.3.4-snapshot+SNAPSHOT
	OpenGL: No OpenGL context found in the current thread
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: Conquest_, STONEBORN - 1.12 - V2.2.zip
	Current Language: Français (France)
	Profiler Position: N/A (disabled)
	CPU: <unknown>
	OptiFine Version: OptiFine_1.12.2_HD_U_G6_pre1
	OptiFine Build: 20210323-161358
	Render Distance Chunks: 16
	Mipmaps: 1
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 4.6.0 NVIDIA 556.12
	OpenGlRenderer: NVIDIA GeForce RTX 4090/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12</details>
