### ISSUE TITLE
subsurface scattering (SSS) problem with complimentary v5.x

### ISSUE THREAD

**Issue by G1ll0u** [fonnymunkey/RLFoliage#6]
Hello,

I have a problem to report.

When this mod is installed, no SSS on most foliage (especially grass)

Normal SSS : 
![image](https://github.com/user-attachments/assets/6f1e71d4-343b-421a-b75d-6a9e800559e2)
Bad SSS :
![image](https://github.com/user-attachments/assets/5d736530-3c4d-4ca8-96d7-bc9b53797b8a)

#https://github.com/ComplementaryDevelopment/ComplementaryReimagined/issues/124
It happens only when BetterFoliage is installed. (I isolated optifine and betterfoliage)
Even if I disable the mod in-game (F8) it doesn't restore SSS...

It was working in previous releases of complementary

I don't know if something could be done here for this problem so I post it and see.

Have a nice day !

**Comment by fonnymunkey** [comment]
The 5.x.x Complementary updates removed compat with older mods, they say as such in the issue tracker you linked along with the solution to it. 

Either downgrade to a 4.x.x version of Complementary that still has mod support for these older mods, or do what the dev said and edit the block.properties file and replace it or the ids with the ones from the older version.

To my knowledge I have no control over Optifine and shader handling of numerical block ids for applying shader effects.

**Comment by G1ll0u** [comment]
Okay, so I fixed that by referencing updated shader block IDs to shader ID in BetterFoliage settings :


<img width="457" height="126" alt="Image" src="https://github.com/user-attachments/assets/39a9fe8d-998e-4985-a405-03fbe4982d4c" />


I don't have access to my computer rn but looking at code, here are the values I modified in F8 menu :
```
object shaders {
    val leavesId by long(min = 1, max = 65535, default = ShadersModIntegration.leavesDefaultBlockId.toInt())
    val grassId by long(min = 1, max = 65535, default = ShadersModIntegration.grassDefaultBlockId.toInt())
    }
```


So I assigned (for the example image above) :
```
leavesID = xxxx9
grassID  =  xxxx5
```

My problem was that I use Complementary Shaders with "Euphoria Patches", it adds compatibility with variety of modded blocks and they changed block IDs in block.properties so I had to put the new value.


So this mod is still BASED imo


Thanks and have a nice day !
